In [181]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from datetime import date
import warnings
warnings.filterwarnings('ignore')

**Thông tin sinh viên**
1. Họ và tên: Phạm Việt Hoàng
2. Mã sinh viên: 2221050346
3. Lớp: DCCTCT67_07B
4. Môn học: Thực tập doanh nghiệp

---
<center>
    <h1> Tiền xử lý, làm sạch dữ liệu</h1>
 </center>
 
1. Dựa vào dữ liệu VTEC_IT_equipment_business đã thu thập được tiến hành tiền xử lý nhằm phục vụ phân tích, trực quan hóa.
2. Bộ dữ liệu gồm các sheet chính:
- orders
- customers
- products
- project
- employees
- suppliers
- inventory

In [187]:
# Đọc dữ liệu
df = pd.read_excel('dataset/IT_equipment_business.xlsx', sheet_name= 'orders')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 348 entries, 0 to 347
Data columns (total 19 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   order_id        348 non-null    object
 1   order_date      348 non-null    datetime64[ns]
 2   customer_id     348 non-null    object
 3   project_id      52 non-null     object
 4   product_id      348 non-null    object
 5   quantity        348 non-null    object
 6   unit_price      348 non-null    object
 7   cost_price      348 non-null    int64
 8   discount        348 non-null    object
 9   revenue         348 non-null    int64
 10  cost            348 non-null    int64
 11  profit          348 non-null    int64
 12  sales_channel   348 non-null    object
 13  payment_method  348 non-null    object
 14  order_status    348 non-null    object
 15  delivery_date   325 non-null    datetime64[ns]
 16  warehouse_id    348 non-null    object
 17  employee_id     348 non-null    object
 18  notes           78 non-null     object
dtypes: datetime64[ns](2), int64(4), object(13)
memory usage: 51.8+ KB

## Nhận thấy cột project_id null khá nhiều, cột notes cũng null nhiều nhưng không phải là vấn đề

In [190]:
df.head(10)

,order_id,order_date,customer_id,project_id,product_id,quantity,unit_price,cost_price,discount,revenue,cost,profit,sales_channel,payment_method,order_status,delivery_date,warehouse_id,employee_id,notes
0,ORD-2023-00100,2023-01-01,CUS0025,NaN,PRD054,16,8000000,6595000,0.05,121600000,105520000,16080000,PARTNER/RESELLER,Chuyển Khoản,Hoàn Thành,2023-06-01,WH01,EMP036,Chiết khấu đặc biệt theo khối lượng / dự án
1,ORD-2024-12465,2023-01-04,CUS0180,NaN,PRD040,12 cái,9000000,7411000,0.05,102600000,88932000,13668000,Sales Representative,Công Nợ 60 Ngày,Hoàn Thành,2023-01-06,WH02,EMP017,NaN
2,ORD-2023-06127,2023-01-05,CUS0155,NaN,PRD009,21,8000000,7013000,0,168000000,147273000,20727000,website b2b portal,Công Nợ 45 Ngày,Hoàn Thành,2023-03-05,WH01,EMP011,NaN
3,ORD-2023-07041,2023-01-08,CUS0062,NaN,PRD078,19,7000000,5954000,0.03,129010000,113126000,15884000,Direct Sales,Công Nợ 15 Ngày,Hoàn Thành,2023-01-12,WH04,EMP030,Chiết khấu đặc biệt theo khối lượng / dự án
4,ORD-2023-03670,2023-01-10,CUS0110,NaN,PRD017,21,4000000,3379000,0.03,81480000,70959000,10521000,Project/Tender,Thanh Toán Theo Tiến Độ Hđ,Hoàn Thành,2023-01-14,WH01,EMP010,Chiết khấu đặc biệt theo khối lượng / dự án
5,ORD-2023-01057,2023-01-14,CUS0117,NaN,PRD065,10,11000000,9324000,0.03,106700000,93240000,13460000,Partner/Reseller,Công Nợ 30 Ngày,Hoàn Thành,2023-01-15,WH01,EMP034,NaN
6,ORD-2023-00291,2023-01-14,CUS0100,-,PRD064,12,11000000,9255000,0.03,128040000,111060000,16980000,Direct Sales,Thanh Toán Theo Tiến Độ Hđ,Hoàn Thành,2023-01-15,WH03,EMP025,NaN
7,ORD-2023-01007,2023-01-15,CUS0012,NaN,PRD022,12,7000000,5944000,0.02,82320000,71328000,10992000,Direct Sales,Công Nợ 30 Ngày,Hoàn Thành,2023-01-20,WH01,EMP016,NaN
8,ORD-2024-09159,2023-01-16,CUS0002,NaN,PRD025,12,10000000,8485000,0.03,116400000,101820000,14580000,Direct Sales,Công Nợ 45 Ngày,Hoàn Thành,2023-01-17,WH03,EMP005,NaN
9,ORD-2024-14221,2023-01-22,CUS0235,NaN,PRD082,10,4000000,3436000,0.02,39200000,34360000,4840000,Sales Representative,Công Nợ 30 Ngày,Đã Giao,2023-01-26,WH01,EMP012,NaN

# 1. Xử lý dữ liệu null

In [193]:
#Thực hiện lọc những project_id bất thường
df.loc[~df['project_id'].str.contains('PRJ', na=False), 'project_id'].unique()

array([nan, '-'], dtype=object)

## Vậy ngoại trừ những id hợp lệ thì chỉ có null và '-', không phải đơn hàng nào cũng có mã dự án nên null không được coi là bất thường

In [196]:
#Thực hiện replace
df['project_id'] = df['project_id'].replace('-', np.nan)

In [198]:
#Kiểm tra lại
df.loc[~df['project_id'].str.contains('PRJ', na=False), 'project_id'].unique()

array([nan], dtype=object)

# 2. Xử lý dữ liệu thiếu nhất quán

In [201]:
df.loc[df['quantity'].str.contains('chiếc|bộ|cái', na = False), 'quantity'].unique()

array(['12 cái', '8 cái', '23 bộ', '27 chiếc', '17 chiếc', '29 chiếc',
       '8 bộ', '16 chiếc', '18 bộ', '23 chiếc', '21 chiếc', '22 cái',
       '10 cái'], dtype=object)

In [203]:
# Sau khi nhận thấy những dòng có chứ ký tự có quy luật số - ' ' - ký tự thì chọn cách tạo hàm split để lấy ra số

In [205]:
#chuyển type qua str 
df['quantity'] = df['quantity'].astype(str)

In [207]:
# Tạo hàm tách chuỗi
def ham_split(x):
    s1 = x.split(' ')
    if len(s1)==2:
        return s1[0]
    else:
        return s1[0]

In [209]:
#apply vào cột quantity
df['quantity'] = df['quantity'].apply(ham_split)

In [211]:
#kiểm tra
df.loc[df['quantity'].str.contains('chiếc|bộ|cái', na = False), 'quantity'].unique()

array([], dtype=object)

In [213]:
#Chuyển lại kiểu int
df['quantity'] = df['quantity'].astype(int)

In [215]:
#Chuyển dữ liệu thiếu nhất quán cột discount
mask = df['discount'].str.contains('%', na=False)

df.loc[mask, 'discount'] = (df.loc[mask, 'discount'].str.replace('%', '', regex=False).astype(float)/ 100)

In [217]:
#chuyển type qua str 
df['unit_price'] = df['unit_price'].astype(str)

In [219]:
#chuyển đổi dữ liệu thiếu nhất quán xóa kỹ hiệu đ
df['unit_price'] = df['unit_price'].apply(ham_split)

In [221]:
#Xóa dấu , chuyển lại về kiểu float
df['unit_price'] = df['unit_price'].str.replace(',', '').astype(float)

## 3. Xử lý dữ liệu dạng text

In [224]:
#Loại bỏ khoảng trắng thừa
df['sales_channel'] = df['sales_channel'].str.strip()

In [226]:
#Loại bỏ khoảng trắng thừ chuyển text về title
df['payment_method'] = df['payment_method'].str.strip().str.title()

In [228]:
#Loại bỏ khoảng trắng thừ chuyển text về title
df['order_status'] = df['order_status'].str.strip().str.title()

In [230]:
#Chuyển định dạng ngày tháng về 1 kiểu đồng nhất
df['order_date'] = pd.to_datetime(df['order_date'],format='mixed',errors='coerce').dt.date
df['delivery_date'] = pd.to_datetime(df['delivery_date'],format='mixed',errors='coerce').dt.date

In [232]:
df.head(10)

,order_id,order_date,customer_id,project_id,product_id,quantity,unit_price,cost_price,discount,revenue,cost,profit,sales_channel,payment_method,order_status,delivery_date,warehouse_id,employee_id,notes
0,ORD-2023-00100,2023-01-01,CUS0025,NaN,PRD054,16,8000000.0,6595000,0.05,121600000,105520000,16080000,PARTNER/RESELLER,Chuyển Khoản,Hoàn Thành,2023-06-01,WH01,EMP036,Chiết khấu đặc biệt theo khối lượng / dự án
1,ORD-2024-12465,2023-01-04,CUS0180,NaN,PRD040,12,9000000.0,7411000,0.05,102600000,88932000,13668000,Sales Representative,Công Nợ 60 Ngày,Hoàn Thành,2023-01-06,WH02,EMP017,NaN
2,ORD-2023-06127,2023-01-05,CUS0155,NaN,PRD009,21,8000000.0,7013000,0,168000000,147273000,20727000,website b2b portal,Công Nợ 45 Ngày,Hoàn Thành,2023-03-05,WH01,EMP011,NaN
3,ORD-2023-07041,2023-01-08,CUS0062,NaN,PRD078,19,7000000.0,5954000,0.03,129010000,113126000,15884000,Direct Sales,Công Nợ 15 Ngày,Hoàn Thành,2023-01-12,WH04,EMP030,Chiết khấu đặc biệt theo khối lượng / dự án
4,ORD-2023-03670,2023-01-10,CUS0110,NaN,PRD017,21,4000000.0,3379000,0.03,81480000,70959000,10521000,Project/Tender,Thanh Toán Theo Tiến Độ Hđ,Hoàn Thành,2023-01-14,WH01,EMP010,Chiết khấu đặc biệt theo khối lượng / dự án
5,ORD-2023-01057,2023-01-14,CUS0117,NaN,PRD065,10,11000000.0,9324000,0.03,106700000,93240000,13460000,Partner/Reseller,Công Nợ 30 Ngày,Hoàn Thành,2023-01-15,WH01,EMP034,NaN
6,ORD-2023-00291,2023-01-14,CUS0100,NaN,PRD064,12,11000000.0,9255000,0.03,128040000,111060000,16980000,Direct Sales,Thanh Toán Theo Tiến Độ Hđ,Hoàn Thành,2023-01-15,WH03,EMP025,NaN
7,ORD-2023-01007,2023-01-15,CUS0012,NaN,PRD022,12,7000000.0,5944000,0.02,82320000,71328000,10992000,Direct Sales,Công Nợ 30 Ngày,Hoàn Thành,2023-01-20,WH01,EMP016,NaN
8,ORD-2024-09159,2023-01-16,CUS0002,NaN,PRD025,12,10000000.0,8485000,0.03,116400000,101820000,14580000,Direct Sales,Công Nợ 45 Ngày,Hoàn Thành,2023-01-17,WH03,EMP005,NaN
9,ORD-2024-14221,2023-01-22,CUS0235,NaN,PRD082,10,4000000.0,3436000,0.02,39200000,34360000,4840000,Sales Representative,Công Nợ 30 Ngày,Đã Giao,2023-01-26,WH01,EMP012,NaN

In [234]:
df['order_status'] = df['order_status'].replace('Đã Giao', 'Hoàn Thành')

## 4. Xử lý dữ liệu trùng lặp

In [237]:
#hiển thị dữ liệu trùng lặp
df[df.duplicated(keep = False)].sort_values('order_id')

,order_id,order_date,customer_id,project_id,product_id,quantity,unit_price,cost_price,discount,revenue,cost,profit,sales_channel,payment_method,order_status,delivery_date,warehouse_id,employee_id,notes
327,ORD-2023-01454,2024-12-29,CUS0122,NaN,PRD097,23,9000000.0,7844000,0,207000000,180412000,26588000,Direct Sales,Công Nợ 30 Ngày,Đang Xử Lý,NaT,WH01,EMP001,NaN
347,ORD-2023-01454,2024-12-29,CUS0122,NaN,PRD097,23,9000000.0,7844000,0,207000000,180412000,26588000,Direct Sales,Công Nợ 30 Ngày,Đang Xử Lý,NaT,WH01,EMP001,NaN
341,ORD-2023-02859,2024-12-20,CUS0115,NaN,PRD037,19,10000000.0,8593000,0.02,186200000,163267000,22933000,Project/Tender,Thanh Toán Theo Tiến Độ Hđ,Hoàn Thành,2024-12-24,WH03,EMP024,Chiết khấu đặc biệt theo khối lượng / dự án
319,ORD-2023-02859,2024-12-20,CUS0115,NaN,PRD037,19,10000000.0,8593000,0.02,186200000,163267000,22933000,Project/Tender,Thanh Toán Theo Tiến Độ Hđ,Hoàn Thành,2024-12-24,WH03,EMP024,Chiết khấu đặc biệt theo khối lượng / dự án
73,ORD-2023-03571,2023-09-01,CUS0092,NaN,PRD005,8,9000000.0,7436000,0.05,68400000,59488000,8912000,Direct Sales,Công Nợ 45 Ngày,Hoàn Thành,2023-09-06,WH01,EMP014,NaN
342,ORD-2023-03571,2023-09-01,CUS0092,NaN,PRD005,8,9000000.0,7436000,0.05,68400000,59488000,8912000,Direct Sales,Công Nợ 45 Ngày,Hoàn Thành,2023-09-06,WH01,EMP014,NaN
331,ORD-2023-06707,2024-02-01,CUS0224,NaN,PRD073,21,8000000.0,7033000,0,168000000,147693000,20307000,Direct Sales,Chuyển Khoản,Hoàn Thành,2024-02-06,WH01,EMP032,NaN
164,ORD-2023-06707,2024-02-01,CUS0224,NaN,PRD073,21,8000000.0,7033000,0,168000000,147693000,20307000,Direct Sales,Chuyển Khoản,Hoàn Thành,2024-02-06,WH01,EMP032,NaN
137,ORD-2024-07418,2023-12-15,CUS0210,NaN,PRD035,18,6000000.0,5211000,0,108000000,93798000,14202000,Direct Sales,Công Nợ 30 Ngày,Hoàn Thành,2023-12-17,WH01,EMP003,NaN
345,ORD-2024-07418,2023-12-15,CUS0210,NaN,PRD035,18,6000000.0,5211000,0,108000000,93798000,14202000,Direct Sales,Công Nợ 30 Ngày,Hoàn Thành,2023-12-17,WH01,EMP003,NaN
337,ORD-2024-07965,2024-12-12,CUS0292,NaN,PRD029,15,10000000.0,8718000,0,150000000,130770000,19230000,Sales Representative,Chuyển Khoản,Hoàn Thành,2024-12-16,WH03,EMP007,NaN
311,ORD-2024-07965,2024-12-12,CUS0292,NaN,PRD029,15,10000000.0,8718000,0,150000000,130770000,19230000,Sales Representative,Chuyển Khoản,Hoàn Thành,2024-12-16,WH03,EMP007,NaN
340,ORD-2024-08291,2024-03-12,CUS0099,NaN,PRD093,13,4000000.0,3287000,0.05,49400000,42731000,6669000,Project/Tender,Chuyển Khoản,Hoàn Thành,2024-03-16,WH01,EMP026,Đơn hàng thuộc gói triển khai PRJ0191
175,ORD-2024-08291,2024-03-12,CUS0099,NaN,PRD093,13,4000000.0,3287000,0.05,49400000,42731000,6669000,Project/Tender,Chuyển Khoản,Hoàn Thành,2024-03-16,WH01,EMP026,Đơn hàng thuộc gói triển khai PRJ0191
55,ORD-2024-08529,2023-07-10,CUS0093,PRJ0013,PRD072,40,7000000.0,5590000,0.08,257600000,223600000,34000000,direct sales,Công Nợ 45 Ngày,Hoàn Thành,2023-07-14,WH01,EMP015,NaN
343,ORD-2024-08529,2023-07-10,CUS0093,PRJ0013,PRD072,40,7000000.0,5590000,0.08,257600000,223600000,34000000,direct sales,Công Nợ 45 Ngày,Hoàn Thành,2023-07-14,WH01,EMP015,NaN
101,ORD-2024-08901,2023-10-23,CUS0237,PRJ0010,PRD023,40,12000000.0,9970000,0.05,456000000,398800000,57200000,Sales Representative,Chuyển Khoản,Hoàn Thành,2023-10-28,WH04,EMP007,NaN
335,ORD-2024-08901,2023-10-23,CUS0237,PRJ0010,PRD023,40,12000000.0,9970000,0.05,456000000,398800000,57200000,Sales Representative,Chuyển Khoản,Hoàn Thành,2023-10-28,WH04,EMP007,NaN
94,ORD-2024-09388,2023-10-11,CUS0219,NaN,PRD055,20,5000000.0,4171000,0.05,95000000,83420000,11580000,website b2b portal,Công Nợ 30 Ngày,Hoàn Thành,2023-12-10,WH01,EMP036,NaN
334,ORD-2024-09388,2023-10-11,CUS0219,NaN,PRD055,20,5000000.0,4171000,0.05,95000000,83420000,11580000,website b2b portal,Công Nợ 30 Ngày,Hoàn Thành,2023-12-10,WH01,EMP036,NaN
338,ORD-2024-10382,2024-12-18,CUS0165,NaN,PRD073,10,7000000.0,5839000,0.05,66500000,58390000,8110000,Project/Tender,Công Nợ 60 Ngày,Hoàn Thành,2024-12-23,WH01,EMP023,NaN
316,ORD-2024-10382,2024-12-18,CUS0165,NaN,PRD073,10,7000000.0,5839000,0.05,66500000,58390000,8110000,Project/Tender,Công Nợ 60 Ngày,Hoàn Thành,2024-12-23,WH01,EMP023,NaN
139,ORD-2024-10529,2023-12-16,CUS0209,NaN,PRD034,19,5000000.0,4144000,0.05,90250000,78736000,11514000,Direct Sales,Công Nợ 30 Ngày,Hoàn Thành,2023-12-18,WH03,EMP030,NaN
332,ORD-2024-10529,2023-12-16,CUS0209,NaN,PRD034,19,5000000.0,4144000,0.05,90250000,78736000,11514000,Direct Sales,Công Nợ 30 Ngày,Hoàn Thành,2023-12-18,WH03,EMP030,NaN
336,ORD-2024-10910,2023-10-03,CUS0239,NaN,PRD056,13,9000000.0,7866000,0,117000000,102258000,14742000,Website B2B Portal,Công Nợ 30 Ngày,Hoàn Thành,2023-10-06,WH01,EMP036,NaN
84,ORD-2024-10910,2023-10-03,CUS0239,NaN,PRD056,13,9000000.0,7866000,0,117000000,102258000,14742000,Website B2B Portal,Công Nợ 30 Ngày,Hoàn Thành,2023-10-06,WH01,EMP036,NaN
219,ORD-2024-11500,2024-07-13,CUS0229,NaN,PRD048,8,8000000.0,6807000,0.02,62720000,54456000,8264000,Website B2B Portal,Chuyển Khoản,Hoàn Thành,2024-07-16,WH04,EMP029,NaN
339,ORD-2024-11500,2024-07-13,CUS0229,NaN,PRD048,8,8000000.0,6807000,0.02,62720000,54456000,8264000,Website B2B Portal,Chuyển Khoản,Hoàn Thành,2024-07-16,WH04,EMP029,NaN
330,ORD-2024-14221,2023-01-22,CUS0235,NaN,PRD082,10,4000000.0,3436000,0.02,39200000,34360000,4840000,Sales Representative,Công Nợ 30 Ngày,Hoàn Thành,2023-01-26,WH01,EMP012,NaN
9,ORD-2024-14221,2023-01-22,CUS0235,NaN,PRD082,10,4000000.0,3436000,0.02,39200000,34360000,4840000,Sales Representative,Công Nợ 30 Ngày,Hoàn Thành,2023-01-26,WH01,EMP012,NaN
260,ORD-2024-14681,2024-10-20,CUS0004,NaN,PRD031,21,5000000.0,4161000,0.05,99750000,87381000,12369000,Partner/Reseller,Công Nợ 15 Ngày,Hoàn Thành,2024-10-21,WH03,EMP036,Chiết khấu đặc biệt theo khối lượng / dự án
344,ORD-2024-14681,2024-10-20,CUS0004,NaN,PRD031,21,5000000.0,4161000,0.05,99750000,87381000,12369000,Partner/Reseller,Công Nợ 15 Ngày,Hoàn Thành,2024-10-21,WH03,EMP036,Chiết khấu đặc biệt theo khối lượng / dự án
46,ORD-2024-14796,2023-06-18,CUS0238,NaN,PRD106,10,8000000.0,6678000,0.05,76000000,66780000,9220000,Direct Sales,Chuyển Khoản,Hoàn Thành,2023-06-22,WH03,EMP001,NaN
333,ORD-2024-14796,2023-06-18,CUS0238,NaN,PRD106,10,8000000.0,6678000,0.05,76000000,66780000,9220000,Direct Sales,Chuyển Khoản,Hoàn Thành,2023-06-22,WH03,EMP001,NaN

In [239]:
#Xử lý dữ liệu trùng lặp giữ lại bản ghi đầu tiên
df = df.drop_duplicates(keep = 'first')

## 5. Ghi đè dữ liệu đã làm sạch vào file cũ

In [242]:
excel_path = 'dataset/IT_equipment_business.xlsx'
sheet_target = 'orders'

# Ghi đè biến df đã làm sạch vào chính sheet 'orders'
with pd.ExcelWriter(
    excel_path,
    engine='openpyxl',
    mode='a',                   # Mở file hiện có để chỉnh sửa
    if_sheet_exists='replace'   # Thay thế/ghi đè sheet cũ, giữ nguyên các sheet khác
) as writer:
    df.to_excel(writer, sheet_name=sheet_target, index=False)

print(f"Đã ghi đè thành công dữ liệu sạch vào sheet '{sheet_target}'!")

Đã ghi đè thành công dữ liệu sạch vào sheet 'orders'!